version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:${DB_PORT}"
    environment:
      - POSTGRES_USER=${SUPER_USER}
      - POSTGRES_PASSWORD=${SUPER_USER_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
  postgrest:
    image: sub0/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      - POSTGREST_DB_HOST=${DB_HOST}
      - POSTGREST_DB_PORT=${DB_PORT}
      - POSTGREST_DB_NAME=${DB_NAME}
      - POSTGREST_SCHEMA=${DB_SCHEMA}
      - POSTGREST_DB_USER=${DB_USER}
      - POSTGREST_DB_PASS=${DB_PASS}
      - POSTGREST_ANONYMOUS=${POSTGREST_ANONYMOUS}
      - POSTGREST_JWT_SECRET=${POSTGREST_JWT_SECRET}
      - POSTGREST_MAX_ROWS=${POSTGREST_MAX_ROWS}
      - POSTGREST_FUNCTION=${POSTGREST_FUNCTION}
      - POSTGREST_POOL=${POSTGREST_POOL}
  openresty:
    image: sub0/dev-openresty
    ports:
      - "8080:80"
    links:
      - db:db
      - postgrest:postgrest
    environment:
      - RELAY_ID_COLUMN=${RELAY_ID_COLUMN}
      - DEVELOPMENT=${DEVELOPMENT}
      - CACHE_BYPASS=${DISABLE_CACHE}
      - POSTGREST_HOST=${POSTGREST_HOST}
      - POSTGREST_PORT=${POSTGREST_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - "./user_module.lua:/usr/local/openresty/lualib/user_module.lua"
      - "./nginx/conf/includes:/usr/local/openresty/nginx/conf/includes"
      - "./frontend/dist:/usr/local/openresty/nginx/html"
      # - "./nginx/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"





