version: '2'
services:
  db:
    image: postgres #official
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      # - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
  postgrest:
    image: sub0/postgrest
    # ports:
    #   - "3000:3000"
    links:
      - db:db
    environment:
      - dummy=true
      # - POSTGREST_SCHEMA=api
      # - POSTGREST_ANONYMOUS=anonymous
      - POSTGREST_JWT_SECRET=secret
      # - POSTGREST_MAX_ROWS=null
      # - POSTGREST_FUNCTION=null
      - POSTGREST_FUNCTION=check_session_id
      # - POSTGREST_POOL=200
      # - POSTGREST_DB_USER=authenticator
      # - POSTGREST_DB_PASS=authenticator
      # - POSTGREST_DB_HOST=db
      # - POSTGREST_DB_PORT=5432
      # - POSTGREST_DB_NAME=app

  openresty:
    image: sub0/openresty
    ports:
      - "8080:80"
    links:
      - db:db
      - postgrest:postgrest
    environment:
      - RELAY_ID_COLUMN=id
      - DEVELOPMENT=0
      # - CACHE_BYPASS=1
      - CACHE_BYPASS=0
      # - POSTGREST_HOST=postgrest
      # - POSTGREST_PORT=3000
      # - DB_SCHEMA=api
      # - DB_HOST=db
      # - DB_PORT=5432
      # - DB_NAME=app
      # - DB_USER=authenticator
      # - DB_PASS=authenticator
    volumes:
      - "./user_module.lua:/usr/local/openresty/lualib/user_module.lua"
      - "./nginx/conf/includes:/usr/local/openresty/nginx/conf/includes"
      - "./frontend/dist:/usr/local/openresty/nginx/html"
      # - "./nginx/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"





